version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=neoproject
      - POSTGRES_USER=neouser
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn neo_9_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot 
volumes:
  pgdata:
  static_volume:
